### ISSUE TITLE
Fix node polling after node has recovered

### ISSUE THREAD

**Issue by Isabello** [filipealmeida/liskak#4]
Currently when a node fails manual intervention is required to bring it back into monitoring.

A fix here to reset stats failure would work

https://github.com/filipealmeida/liskak/blob/master/src/liskak.js#L930

or here we can test the results of the polling instead and check if its disabled but has good stats. if we get good stats it should be reinstated.

https://github.com/filipealmeida/liskak/blob/master/src/liskak.js#L987

**Comment by filipealmeida** [comment]
Please check if it works, opted for the runtime stats jolt at #930
